spring.application.name=auth-server
server.port=9000

spring.security.oauth2.authorizationserver.client.market-client.registration.client-id=market-app
spring.security.oauth2.authorizationserver.client.market-client.registration.client-secret={noop}market-secret

spring.security.oauth2.authorizationserver.client.market-client.registration.client-authentication-methods=client_secret_basic
spring.security.oauth2.authorizationserver.client.market-client.registration.authorization-grant-types=client_credentials
spring.security.oauth2.authorizationserver.client.market-client.registration.scopes=payment:read,payment:write