spring.application.name=my-market-app

# R2DBC Configuration (?????????? ???????????)
spring.r2dbc.url=r2dbc:h2:mem:///marketdb;DB_CLOSE_DELAY=-1
spring.r2dbc.username=sa
spring.r2dbc.password=

# ????????????? ?????
spring.sql.init.mode=always

# Thymeleaf
spring.thymeleaf.cache=false

# Server
server.port=8080

logging.level.org.springframework.web=DEBUG